version: '3'
services:
  rabbitmq:
    image: tutum/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_PASS=mypass
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
